kind: Service
apiVersion: v1
metadata: 
  name: nginx
spec:
  selector:
      app: nginx
      tier: web
      project: test-project
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.configmap.port }}